[book]
authors = ["Soares Chen"]
language = "en"
multilingual = false
src = "code"
title = "Scrive Nix Workshop"

[build]
create-missing = false
build-dir = "./book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
